# Generated by Django 4.0.4 on 2022-05-18 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyOrganization',
            fields=[
                ('organization_name', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('type_study_organization', models.CharField(choices=[('U', 'University'), ('S', 'School'), ('S', 'College')], default='S', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Specialisation',
            fields=[
                ('specialisation_name', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('study_time', models.IntegerField()),
                ('specialisation_study_organization', models.ManyToManyField(blank=True, to='blogposting.studyorganization')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('status', models.CharField(choices=[('B', 'Bachelor'), ('M', 'Master'), ('PHD', 'PhD')], default='M', max_length=3)),
                ('bio', models.TextField(blank=True)),
                ('specialisation', models.ManyToManyField(blank=True, to='blogposting.specialisation')),
                ('study_organizations', models.ManyToManyField(blank=True, to='blogposting.studyorganization')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blogposting.author')),
            ],
        ),
    ]
