# Generated by Django 4.0.4 on 2022-07-19 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('blogposting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('authors', models.ManyToManyField(blank=True, to='blogposting.author')),
                ('specialisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogposting.specialisation')),
            ],
        ),
        migrations.AlterField(
            model_name='studyorganization',
            name='type_study_organization',
            field=models.CharField(choices=[('U', 'University'), ('S', 'School'), ('C', 'College')], default='S', max_length=3),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.TextField(blank=True)),
                ('course', models.ManyToManyField(blank=True, to='blogposting.course')),
                ('specialisation', models.ManyToManyField(blank=True, to='blogposting.specialisation')),
                ('study_organization', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='blogposting.studyorganization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='course',
            name='study_organizations',
            field=models.ManyToManyField(to='blogposting.studyorganization'),
        ),
    ]
